# Generated by Django 2.0 on 2018-03-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CourseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detail.CourseDetails'),
        ),
    ]
