# Generated by Django 2.0 on 2018-03-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20180316_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CourseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.CourseDetails'),
        ),
    ]
